# Generated by Django 5.2.1 on 2025-06-11 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_brand_product_cart_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_type',
            field=models.CharField(choices=[('UZS', "O'zbek so'mi"), ('USD', 'Aqsh Dollori'), ('RUB', 'Rossiya Rubli')], default='UZS', max_length=3),
        ),
    ]
